export interface Artwork {
  id: string;
  title: {
    fr: string;
    en: string;
    wo: string;
  };
  origin: {
    region: string;
    country: string;
    coordinates: [number, number];
  };
  category: 'royalty' | 'spirituality' | 'daily' | 'celebration';
  image: string;
  description: {
    fr: string;
    en: string;
    wo: string;
  };
  audio: {
    fr: string;
    en: string;
    wo: string;
  };
  video?: string;
  period?: string;
  materials?: string[];
  dimensions?: string;
  culturalContext?: {
    fr: string;
    en: string;
    wo: string;
  };
  provenance?: {
    fr: string;
    en: string;
    wo: string;
  };
  curatorNotes?: {
    fr: string;
    en: string;
    wo: string;
  };
  museum?: {
    name: string;
    city: string;
    country: string;
  };
  timeline: Array<{
    year: string;
    event: {
      fr: string;
      en: string;
      wo: string;
    };
    icon: string;
  }>;
  relatedArtworks: string[];
  tags: string[];
}

// Import images from the Oeuvres_MCN folder to populate the gallery
import img1 from '../../Oeuvres_MCN/9132b745-c338-4ab4-b485-e559584e5ae0.jpg';
import img2 from '../../Oeuvres_MCN/fc432193-2811-404d-afe4-3f3364ca34d3.jpg';
import img3 from '../../Oeuvres_MCN/368e6c01-8120-4677-8426-dac978597785.jpg';
import img4 from '../../Oeuvres_MCN/494064d5-5431-4864-b1b8-1ffcab84421c.jpg';
import img5 from '../../Oeuvres_MCN/f163e4ce-53f6-4d3e-a337-941276d0580b.jpg';
import img6 from '../../Oeuvres_MCN/ffa3ca5c-2191-41b3-8666-7f25282336d4.jpg';
import img7 from '../../Oeuvres_MCN/67a363e1-ad2e-42e9-9604-470dad610757.jpg';
import img8 from '../../Oeuvres_MCN/41ef8a9f-d5b0-44e0-898d-03d8f63c0e02.jpg';
import img9 from '../../Oeuvres_MCN/24f3b048-6ac8-416d-a719-0d1fd4c481d1.jpg';
import img10 from '../../Oeuvres_MCN/f4242d92-f3d7-42ff-8035-10d51bd04c54.jpg';
import img11 from '../../Oeuvres_MCN/daef7562-164e-47cf-bcfa-30a0ba7e1efe.jpg';
import img12 from '../../Oeuvres_MCN/18ce50e7-c7a3-41fb-a858-7041ea0b1c0a.jpg';
import img13 from '../../Oeuvres_MCN/8b42af43-87a2-4043-83e7-33f1213afd13.jpg';

const importedImages: string[] = [
  img1,
  img2,
  img3,
  img4,
  img5,
  img6,
  img7,
  img8,
  img9,
  img10,
  img11,
  img12,
  img13,
];

const categories: Array<Artwork['category']> = ['royalty', 'spirituality', 'daily', 'celebration'];

function createAutogeneratedArtwork(index: number, imagePath: string): Artwork {
  const category = categories[index % categories.length];
  const id = `mcn-${index + 1}`;
  const baseTitle = `Œuvre MCN ${index + 1}`;
  const detailFr = `Œuvre ${index + 1} des collections du Musée des Civilisations Noires (Dakar, Sénégal). Cette pièce illustre la richesse des savoir-faire transmis de génération en génération. Les matériaux et la facture renvoient à des usages sociaux, rituels ou royaux selon les régions. Exposée à Dakar, elle témoigne d’un patrimoine vivant en dialogue avec le présent.`;
  const detailEn = `Artwork ${index + 1} from the Museum of Black Civilizations (Dakar, Senegal). This piece showcases craftsmanship passed down through generations. Its materials and making refer to social, ritual, or royal uses depending on the region. Exhibited in Dakar, it reflects a living heritage in dialogue with the present.`;
  const detailWo = `Œuvre ${index + 1} ci Musée des Civilisations Noires (Dakar, Sénégal). Mi ngi wone njaay wu ëmb gi ñu jël ci ay xel ak loxo yu yaay ba doom. Matéer yi ak lacc yi di jëfandikookoon ci wàll social, ritual walla royauté. Ñu wone ko ci Dakar, di biral patrimwaan bu di wax ak leegi.`;

  const timeline: Artwork['timeline'] = [
    { year: 'Origines', event: { fr: 'Transmission des savoir-faire', en: 'Transmission of skills', wo: 'Jox xam-xam yi' }, icon: '🌍' },
    { year: 'Création', event: { fr: 'Réalisation de la pièce', en: 'Creation of the piece', wo: 'Sampu kër gi' }, icon: '🛠️' },
    { year: 'Aujourd’hui', event: { fr: 'Mise en valeur au MCN, Dakar', en: 'Showcased at MBC, Dakar', wo: 'Wone ko ci MCN, Dakar' }, icon: '🏛️' }
  ];

  return {
    id,
    title: {
      fr: baseTitle,
      en: `Artwork MCN ${index + 1}`,
      wo: `Œuvre MCN ${index + 1}`
    },
    origin: {
      region: 'Afrique',
      country: 'Afrique',
      coordinates: [0, 0]
    },
    category,
    image: imagePath,
    description: {
      fr: detailFr,
      en: detailEn,
      wo: detailWo
    },
    audio: {
      fr: `/audio/${id}-fr.mp3`,
      en: `/audio/${id}-en.mp3`,
      wo: `/audio/${id}-wo.mp3`
    },
    video: `/video/${id}.mp4`,
    period: 'Contemporain',
    materials: ['Bois', 'Métal', 'Textile'],
    dimensions: 'N/A',
    culturalContext: {
      fr: 'Contexte culturel générique pour la démonstration.',
      en: 'Generic cultural context for demonstration.',
      wo: 'Contexte culturel générique bu demo.'
    },
    provenance: {
      fr: 'Collection du Musée des Civilisations Noires.',
      en: 'Collection of the Museum of Black Civilizations.',
      wo: 'Collection Musée des Civilisations Noires.'
    },
    curatorNotes: {
      fr: 'Note du conservateur: description à affiner.',
      en: 'Curator note: description to refine.',
      wo: 'Note conservateur: description a bokk.'
    },
    museum: {
      name: 'Musée des Civilisations Noires',
      city: 'Dakar',
      country: 'Sénégal'
    },
    timeline,
    relatedArtworks: [],
    tags: ['mcn']
  };
}

const autogeneratedArtworks: Artwork[] = importedImages.map((img, i) => createAutogeneratedArtwork(i, img));

export const artworks: Artwork[] = [...autogeneratedArtworks];
